### ISSUE TITLE
"map techbased" crashes the game on Yamagi 8.20

### ISSUE THREAD

**Issue by protocultor** [glhrmfrts/q25_game#8]
Arrived at the point in the game where I opened the portal after acquiring the "5 keys", but the game crashes when entering in it. The "current" savegame tries to load "techbased", so I tried to load it manually, and again, the game crashes.
Logs don't provide anything useful:
```
]map techbased
-------- game initialization -------
==== InitGame Q25 ====
cvar gl_clear ist deprecated, use r_clear instead
------------------------------------

------- server initialization ------
0 entities inhibited
0 teams repaired
0 teams with 0 entities
------------------------------------

[0.0.0.0]:0: client_connect


-==================
```
That's it. I'm using the DLL you've included in your release. Anything you need to troubleshoot this, just ask.
This occurs with official Yamagi 8.20 release, and the latest "master" branch, manually compiled. I haven't tried to compile your DLL since I don't have VS 2019.

**Comment by nephatrine** [comment]
@protocultor This is all set up for cmake so if you're able to manually compile yamagi, then I'd expect you should be able to manually compile this with the same compiler. It's probably not super robust, but I'm happy to assist. I can't reproduce this specific error though on my end.

**Comment by protocultor** [comment]
> @protocultor This is all set up for cmake so if you're able to manually compile yamagi, then I'd expect you should be able to manually compile this with the same compiler. It's probably not super robust, but I'm happy to assist.
> 
> ~I can't reproduce this specific error though on my end.~ Nevermind, I totally can and will try to t/s.

Just in case: since a good while, Yamagi only uses "make", and they have been trying to get rid of CMake, but have never made it official. I'll install CMake in this MSYS2 environment and try to make it work, anyway.
Many thanks for taking a look.

**Comment by nephatrine** [comment]
I find cmake much friendlier than plain make for cross-platform projects since it's supported easily in Linux environments as well as in Visual Studio on Windows, but I do get that it is one more thing to install whereas make comes out-of-the-box on many platforms.

I'm getting this segfault when I try to load `techbased`:

```
Thread 1 received signal SIGSEGV, Segmentation fault.
S_GetVolume (sound_volume=<optimized out>, width=<optimized out>, sound_length=<optimized out>, data=<optimized out>) at C:/MSYS64/home/nephatrine/Q2/yquake2/src/client/sound/sound.c:263
263                             short sound_sample = LittleShort(*sound_data);
```
Since it's only this engine that I'm aware of that has this issue, I'm tempted to say it's on their end... but I'll try to take a deeper look with a fully debug build.

**Comment by nephatrine** [comment]
@protocultor  If you replace the `sound/goreshit.wav` in the mod folder with this one, are you able to load and play that level?
[goreshit.zip](https://github.com/glhrmfrts/q25_game/files/11226919/goreshit.zip)

**Comment by protocultor** [comment]
@nephatrine yes, it loads inmediately without issue. It was the "stereo" sound.
Many thanks for the quick fixing!
